# Generated by Django 3.1.4 on 2020-12-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=120)),
            ],
        ),
    ]
