# Generated by Django 3.1.4 on 2020-12-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone_number',
            field=models.CharField(default='', max_length=30),
        ),
    ]
